import { DEFAULT_PAINT_PARAMS, type PaintParams } from "./types";

export interface Preset {
  id: string;
  name: string;
  params: PaintParams;
}

/**
 * One-click starting points.
 * Values are hand-tuned against rendered test scenes;
 * every preset is just a slider configuration - there is no hidden logic behind them.
 * All brush presets drive the physics-based SBR renderer;
 * the legacy per-pixel LIC filter remains reachable through the mode selector only.
 */
export const PRESETS: Preset[] = [
  {
    id: "classic-oil",
    name: "Classic Oil",
    params: { ...DEFAULT_PAINT_PARAMS },
  },
  {
    id: "oil-impasto-sbr",
    name: "Oil Impasto (SBR)",
    params: {
      ...DEFAULT_PAINT_PARAMS,
      kuwaharaRadius: 4,
      edgeQ: 8,
      pigments: 24,
      saturation: 1.3,
      contrast: 1.1,
      impastoDepth: 70,
      lightElevation: 40,
      lightAzimuth: 130,
      specular: 0.45,
      shininess: 40,
      bristle: 0.7,
      canvasWeave: 0.15,
      cavity: 0.6,
      pigmentNoise: 0.35,
      noiseScale: 8,
      knifeSize: 36,
      sbrAlignment: 0.85,
      knifeDryness: 0.3,
      knifeDrag: 0.5,
      paintVibrancy: 0.7,
      brushAnisotropy: 0.7,
      edgeFringe: 0.4,
    },
  },
  {
    id: "thick-impasto",
    name: "Thick Impasto",
    params: {
      ...DEFAULT_PAINT_PARAMS,
      kuwaharaRadius: 6,
      edgeQ: 10,
      pigments: 16,
      saturation: 1.25,
      contrast: 1.1,
      impastoDepth: 85,
      lightElevation: 35,
      specular: 0.45,
      shininess: 20,
      bristle: 0.85,
      canvasWeave: 0.25,
      cavity: 0.8,
      pigmentNoise: 0.6,
      noiseScale: 10,
      knifeSize: 48,
      knifeDryness: 0.4,
      knifeDrag: 0.55,
      paintVibrancy: 0.7,
      brushAnisotropy: 0.7,
      edgeFringe: 0.45,
    },
  },
  {
    id: "palette-knife",
    name: "Palette Knife",
    params: {
      ...DEFAULT_PAINT_PARAMS,
      mode: "knife",
      kuwaharaRadius: 4,
      edgeQ: 8,
      strokeLength: 0,
      pigments: 26,
      saturation: 1.5,
      contrast: 1.2,
      impastoDepth: 32,
      specular: 0.35,
      shininess: 36,
      bristle: 0,
      canvasWeave: 0,
      cavity: 0.4,
      pigmentNoise: 0.3,
      noiseScale: 10,
      knifeSize: 40,
      knifeDetail: 0.65,
      knifeRidge: 0.7,
      knifeDryness: 0.35,
      knifeDrag: 0.5,
      paintVibrancy: 0.7,
      brushAnisotropy: 0.4,
      edgeFringe: 0.35,
    },
  },
  {
    id: "fine-brush",
    name: "Fine Brush",
    params: {
      ...DEFAULT_PAINT_PARAMS,
      kuwaharaRadius: 3,
      edgeQ: 6,
      pigments: 36,
      saturation: 1.15,
      contrast: 1.05,
      impastoDepth: 30,
      specular: 0.25,
      shininess: 32,
      bristle: 0.5,
      canvasWeave: 0.35,
      weaveScale: 3,
      cavity: 0.35,
      pigmentNoise: 0.3,
      noiseScale: 6,
      knifeSize: 20,
      sbrAlignment: 0.9,
      sbrDetailDensity: 1.5,
      knifeDryness: 0.2,
      knifeDrag: 0.4,
      edgeFringe: 0.3,
    },
  },
  {
    id: "soft-wash",
    name: "Soft Wash",
    params: {
      ...DEFAULT_PAINT_PARAMS,
      kuwaharaRadius: 8,
      edgeQ: 2,
      pigments: 28,
      saturation: 1.05,
      contrast: 1.0,
      impastoDepth: 18,
      specular: 0.1,
      shininess: 16,
      bristle: 0.25,
      canvasWeave: 0.55,
      weaveScale: 5,
      cavity: 0.25,
      pigmentNoise: 0.4,
      noiseScale: 12,
      knifeSize: 44,
      sbrDetailDensity: 0.5,
      knifeDryness: 0.1,
      knifeDrag: 0.6,
      brushAnisotropy: 0.3,
      edgeFringe: 0.15,
    },
  },
];
